spring:
  application:
    name: springboot-jpa N-plus-One
  datasource:
    url: jdbc:mysql://localhost:3306/yourdatabase
    username: yourname
    password: yourpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
