spring:
  application:
    name: springboot-jpa N-plus-One
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
